### ISSUE TITLE
can I find intrinsic calibration using a single image ?

### ISSUE THREAD

**Issue by arjunskumar** [OpenCalib/CalibAnything#1]

**Comment by xiaokn** [comment]
> _No description provided._

I don't understand what you mean!

**Comment by arjunskumar** [comment]
@xiaokn how can I find intrinsic parameters (cx,cy, fx, fy)of the camera ?

**Comment by xiaokn** [comment]
> @xiaokn how can I find intrinsic parameters (cx,cy, fx, fy)of the camera ?

there is a calib.txt under data sample folder
