### ISSUE TITLE
T in calib.txt

### ISSUE THREAD

**Issue by Capchenxi** [OpenCalib/CalibAnything#2]
Hello, 

Thinks for your excellent work. I noticed that there were 12 elements in T matrix in calib.txt file. Are these elements the 3 x 4 Transform matrix concatenated horizontally or vertically? Thanks.

**Comment by MRZHUGH** [comment]
Based on personal experience, it should be a horizontal connection. for example:
| Rotation | Rotation | Rotation | translation(xyz)|
|--------|--------|--------|--------|
| 0.0188623 | -0.999822 | -9.36529e-05| -0.0323222 |
| 0.0288601| 0.000638227 | -0.999583 | -0.396685 |
| 0.999405 | 0.0188516 | 0.028867| -0.0869361 | 

_from CalibAnything/data/ours/1/calib.txt_

**Comment by sisyphus-99** [comment]
Yes, it is the 3x4 transformation matrix concatenated horizontally.

**Comment by MRZHUGH** [comment]
您好，我已收到您的邮件，我会尽快给您回复的。祝 工作顺利 生活愉快！

**Comment by MRZHUGH** [comment]
您好，我已收到您的邮件，我会尽快给您回复的。祝 工作顺利 生活愉快！
