### ISSUE TITLE
打开dir失败问题

### ISSUE THREAD

**Issue by completezealous** [OpenCalib/CalibAnything#4]
我已经成功编译  但是运行../run_lidar2camera ./data/ours/1 出现错误
![image](https://github.com/OpenCalib/CalibAnything/assets/56358219/688717e2-7c66-471d-aa45-18c7175e9f9a)
![image](https://github.com/OpenCalib/CalibAnything/assets/56358219/e5ddbeea-489b-4f36-8249-4a0990ec754c)
 opencv是3.4

**Comment by completezealous** [comment]
我设置为绝对路径后 解决了这个问题  但是又出现了新的问题 
![image](https://github.com/OpenCalib/CalibAnything/assets/56358219/7e261163-0ee9-44a3-bfd9-642ac1919fcd)
我感觉还是路径设置问题

**Comment by sisyphus-99** [comment]
抱歉，README中写的不够准确，现已修改。
请在CalibAnything目录下运行
```
./bin/run_lidar2camera  ./data/kitti/1
```

**Comment by af-doom** [comment]
> 我设置为绝对路径后 解决了这个问题 但是又出现了新的问题 ![image](https://user-images.githubusercontent.com/56358219/245460232-7e261163-0ee9-44a3-bfd9-642ac1919fcd.png) 我感觉还是路径设置问题

您好，您在自己数据上完成标定了吗，效果如何

**Comment by completezealous** [comment]
> > 我设置为绝对路径后 解决了这个问题 但是又出现了新的问题 ![image](https://user-images.githubusercontent.com/56358219/245460232-7e261163-0ee9-44a3-bfd9-642ac1919fcd.png) 我感觉还是路径设置问题
> 
> 您好，您在自己数据上完成标定了吗，效果如何

效果不太理想，本身我们采集多模态数据的方法就不完善
