### ISSUE TITLE
Why does the shock coefficient have 4 parameters, shouldn’t it be 5?

### ISSUE THREAD

**Issue by sumenpuyuan** [OpenCalib/CalibAnything#5]

**Comment by sisyphus-99** [comment]
We use the `initUndistortRectifyMap` in opencv to undistort the image. The order of the distortion coefficients is consistent with the input requirement of this function: 
```
Input vector of distortion coefficients:
[k1,k2,p1,p2,k3,k4,k5,k6,s1,s2,s3,s4,taux,tauy] of 4, 5, 8, 12 or 14 elements. 
If the vector is empty, the zero distortion coefficients are assumed.
```
reference link: https://amroamroamro.github.io/mexopencv/matlab/cv.initUndistortRectifyMap.html
